service: 'coreservice-accounts'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: stage
  lambdaHashingVersion: '20201221'
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-webpack-prisma

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    noPrependStageInUrl: true

functions:
  app:
    handler: src/index.handler
    events:
      - http: 'ANY /'
      - http: 'ANY /{proxy+}'
  scheduler:
    handler: src/scheduler.handler
    events:
      - schedule:
          enabled: true
          rate: cron(0 6 ? * 2-6 *)
