service: 'coreservice-accounts'
useDotenv: true

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-northeast-2
  stage: stage
  timeout: 16
  apiGateway:
    shouldStartNameWithService: true

package:
  individually: true

plugins:
  - serverless-webpack
  - serverless-webpack-prisma
  - serverless-doppler
  - serverless-offline

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
  serverless-offline:
    noPrependStageInUrl: true

functions:
  app:
    handler: src/index.handler
    events:
      - http:
          method: ANY
          path: '{proxy+}'
  passExtendScheduler:
    handler: src/schedulers/passExtend.onPassExtendScheduler
    events:
      - schedule:
          enabled: true
          rate: cron(0 6 ? * 2-6 *)
  levelUpdateScheduler:
    handler: src/schedulers/levelUpdate.onLevelUpdateScheduler
    events:
      - schedule:
          enabled: true
          rate: cron(0 0 1 * ? *)
